spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/library
    username: usr
    password: pwd
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
minio:
  minioServer:
    host: localhost
    port: 9000
    bucket: library
  minioUser:
    login: devuser
    password: devuserpassword